### ISSUE TITLE
Add high-level documentation

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/timeseer-ansible-collection#1]
Document why there are three different roles for Docker and in which situations which roles are required.

**Comment by DiogoLobo122** [comment]
- [ ] Deploy Timeseer using Docker as per the roles and documentation provided. Take notes of any bugs found or missing documentation, and provide commentary.

- [ ] Deploy Timeseer using Podman as per the roles and documentation provided. Take notes of any bugs found or missing documentation, and provide commentary.

- [ ] You will need to SSH into the VM and install Docker first, also log in to our repository with your credentials.

- [ ] Check the Python version and install pip if it is a new VM.

- [ ] Install Docker SDK for Python

- [ ] For Podman, you will need container tools.

**Comment by fombas** [comment]
@jhoekx  @lucasKoeb

**Comment by jhoekx** [comment]
The data service role documentation and defaults include a `timeseer_data_service_enable` variable that is set to `false` by default according to the documentation. It looks like that variable is not working.

We should default it to `true`.

**Comment by jhoekx** [comment]
I tried to use the roles in a minimal Ansible installation (only Ansible core). I needed to run `ansible-galaxy collection install community.docker`. I think it should be a dependency or our `timeseer.docker` collection.

**Comment by smeganck** [comment]
@lucasKoeb

**Comment by lucasKoeb** [comment]
Validated, used the data service and timeseer roles using some of the documented options and it worked as expected. The sample playbooks on the documentation worked.
