### ISSUE TITLE
Create a CI GitHub pipeline to release the collection

### ISSUE THREAD

**Issue by DiogoLobo122** [timeseer-ai/timeseer-ansible-collection#13]
- [x] Lint every build 
- [x] Package 
- [x] upload the tar file to  the action page
- [x] use the build in each collection dir instead of using in the root
- [x] build podman as well, for now we are only building docker  - check galaxy.yml  /cd and build
- [x] add a release pipeline with build and test as well

**Comment by smeganck** [comment]
@jhoekx
