### ISSUE TITLE
Traefik role should not listen for Flight port when Flight is not enabled

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/timeseer-ansible-collection#17]
We currently listen on port 8443, even though Flight is not enabled. This can lead to port conflicts.

https://github.com/timeseer-ai/timeseer-ansible-collection/blob/8d9440eb3c1468d40d7b6add2fea10e778cdef4e/timeseer/docker/roles/traefik/tasks/main.yml#L51

**Comment by smeganck** [comment]
@jhoekx

**Comment by jhoekx** [comment]
Validated by listing used ports on internal environments. Port 8443 was no longer listened on.
