### ISSUE TITLE
Add an option to use use your own Certificates with Traefik 

### ISSUE THREAD

**Issue by DiogoLobo122** [timeseer-ai/timeseer-ansible-collection#6]
Currently, we only had the option to use Traefik with the ACME protocol in the collection

**Comment by smeganck** [comment]
@lucasKoeb - Docker and Podman

**Comment by lucasKoeb** [comment]
Documentation is not updated, `traefik_tls` and the variables required for each option (`certs`/`acme`) are not there.
It still lists the `traefik_letsencrypt_mail` as mandatory, which is now only true if `traefik_tls = acme`.

Functionality validated on the docker version, using a self signed certificate worked.

**Comment by smeganck** [comment]
@lucasKoeb

**Comment by lucasKoeb** [comment]
Validated, the new options are in the documentation.
