### ISSUE TITLE
Allow exposing reverse proxy ports

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/timeseer-ansible-collection#9]
In setups without Traefik, we might want to configure the Timeseer Reverse Proxy as the public endpoint. Similarly to how we allow exposing Timeseer container ports, allow exposing the Reverse Proxy ports.

**Comment by jhoekx** [comment]
This was only done for Podman?

**Comment by DiogoLobo122** [comment]
> This was only done for Podman?

Sorry, I forgot to update. The Docker role is done now. Thanks for pointing this out.

**Comment by smeganck** [comment]
@jhoekx

**Comment by jhoekx** [comment]
Validated in https://github.com/timeseer-ai/timeseer-installer/commit/50e49e2cbfb8a3d6674db0d2cde04f4ab731762c
